/*
-- Query: SELECT * 
FROM awardsplayers
WHERE playerID IN ('correca01','colege01','harpebr03','strasst01','beckhti01','priceda01','hochelu01','uptonju01','bushma01','youngde03','bullibr01','mauerjo01','gonzaad01','hamiljo03','burrepa01','anderma01','erstada01','wilsopa02','rodrial01','nevinph01','jonesch06','mcdonbe01','benesan01','griffke02','kingje01','surhobj01','abnersh01','belchti01','dunstsh01','mooremi01','strawda01','chambal01')
ORDER BY playerID
LIMIT 0, 50000

-- Date: 2019-02-27 19:37
*/
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('correca01','Rookie of the Year',2015,'AL','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('dunstsh01','TSN All-Star',1989,'NL','','SS');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('erstada01','Gold Glove',2000,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('erstada01','Silver Slugger',2000,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('erstada01','TSN All-Star',2000,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('erstada01','Gold Glove',2002,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('erstada01','Gold Glove',2004,'AL','','1B');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('gonzaad01','Gold Glove',2008,'NL','','1B');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('gonzaad01','Gold Glove',2009,'NL','','1B');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('gonzaad01','Gold Glove',2011,'AL','','1B');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('gonzaad01','Silver Slugger',2011,'AL','','1B');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('gonzaad01','Gold Glove',2014,'NL','','1B');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('gonzaad01','Silver Slugger',2014,'NL','','1B');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','Gold Glove',1990,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','Gold Glove',1991,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','Silver Slugger',1991,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','TSN All-Star',1991,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','All-Star Game MVP',1992,'ML','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','Gold Glove',1992,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','Gold Glove',1993,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','Silver Slugger',1993,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','TSN All-Star',1993,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','Gold Glove',1994,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','Silver Slugger',1994,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','TSN All-Star',1994,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','Gold Glove',1995,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','Gold Glove',1996,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','Silver Slugger',1996,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','TSN All-Star',1996,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','Gold Glove',1997,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','Most Valuable Player',1997,'AL','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','Silver Slugger',1997,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','TSN All-Star',1997,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','TSN Major League Player of the Year',1997,'ML','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','Gold Glove',1998,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','Silver Slugger',1998,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','TSN All-Star',1998,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','Gold Glove',1999,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','Silver Slugger',1999,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','TSN All-Star',1999,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','Comeback Player of the Year',2005,'NL','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('griffke02','TSN All-Star',2005,'NL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('hamiljo03','Silver Slugger',2008,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('hamiljo03','ALCS MVP',2010,'AL','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('hamiljo03','Most Valuable Player',2010,'AL','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('hamiljo03','Silver Slugger',2010,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('hamiljo03','TSN Major League Player of the Year',2010,'ML','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('hamiljo03','Silver Slugger',2012,'AL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('harpebr03','Rookie of the Year',2012,'NL','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('harpebr03','Hank Aaron Award',2015,'ML','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('harpebr03','Most Valuable Player',2015,'NL','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('harpebr03','Silver Slugger',2015,'NL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('jonesch06','Most Valuable Player',1999,'NL','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('jonesch06','Silver Slugger',1999,'NL','','3B');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('jonesch06','TSN All-Star',1999,'NL','','3B');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('jonesch06','Silver Slugger',2000,'NL','','3B');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('jonesch06','TSN All-Star',2000,'NL','','3B');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('jonesch06','TSN All-Star',2001,'NL','','3B');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('mauerjo01','Silver Slugger',2006,'AL','','C');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('mauerjo01','TSN All-Star',2006,'AL','','C');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('mauerjo01','Gold Glove',2008,'AL','','C');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('mauerjo01','Silver Slugger',2008,'AL','','C');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('mauerjo01','Gold Glove',2009,'AL','','C');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('mauerjo01','Most Valuable Player',2009,'AL','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('mauerjo01','Silver Slugger',2009,'AL','','C');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('mauerjo01','Gold Glove',2010,'AL','','C');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('mauerjo01','Silver Slugger',2010,'AL','','C');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('mauerjo01','Silver Slugger',2013,'AL','','C');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('priceda01','Cy Young Award',2012,'AL','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('priceda01','TSN Pitcher of the Year',2012,'AL','Y','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Silver Slugger',1996,'AL','','SS');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','TSN All-Star',1996,'AL','','SS');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','TSN Major League Player of the Year',1996,'ML','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Silver Slugger',1998,'AL','','SS');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','TSN All-Star',1998,'AL','','SS');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Silver Slugger',1999,'AL','','SS');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Silver Slugger',2000,'AL','','SS');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','TSN All-Star',2000,'AL','','SS');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Hank Aaron Award',2001,'AL','','SS');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Silver Slugger',2001,'AL','','SS');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','TSN All-Star',2001,'AL','','SS');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Gold Glove',2002,'AL','','SS');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Hank Aaron Award',2002,'AL','','Ss');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Silver Slugger',2002,'AL','','SS');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','TSN All-Star',2002,'AL','','SS');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','TSN Major League Player of the Year',2002,'ML','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Gold Glove',2003,'AL','','SS');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Hank Aaron Award',2003,'AL','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Most Valuable Player',2003,'AL','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Silver Slugger',2003,'AL','','SS');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','TSN All-Star',2003,'AL','','SS');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Most Valuable Player',2005,'AL','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Silver Slugger',2005,'AL','','3B');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','TSN All-Star',2005,'AL','','3B');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Hank Aaron Award',2007,'AL','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Most Valuable Player',2007,'AL','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Silver Slugger',2007,'AL','','3B');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','TSN All-Star',2007,'AL','','3B');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','TSN Major League Player of the Year',2007,'ML','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Silver Slugger',2008,'AL','','3B');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('rodrial01','Babe Ruth Award',2009,'AL','','3B');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('strasst01','Silver Slugger',2012,'NL','','P');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('strawda01','Rookie of the Year',1983,'NL','','');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('strawda01','Silver Slugger',1988,'NL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('strawda01','TSN All-Star',1988,'NL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('strawda01','Silver Slugger',1990,'NL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('strawda01','TSN All-Star',1990,'NL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('uptonju01','Silver Slugger',2011,'NL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('uptonju01','Silver Slugger',2014,'NL','','OF');
INSERT INTO `` (`playerID`,`awardID`,`yearID`,`lgID`,`tie`,`notes`) VALUES ('youngde03','ALCS MVP',2012,'AL','','');
